# Generated by Django 4.0.1 on 2022-01-18 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_alter_game_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1ea7da08-6ba1-4948-8917-51ba0814f34a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d5fcfca5-2fd9-4562-8611-865d20e1fa63'), editable=False, primary_key=True, serialize=False),
        ),
    ]
