# Generated by Django 4.0.1 on 2022-01-19 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0004_alter_game_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='words',
            name='frequency',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a843b14f-648c-4d45-9f71-b634d22c608a'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c2e9f0ab-80ae-43e4-a51d-24031bcba7ec'), editable=False, primary_key=True, serialize=False),
        ),
    ]
