# Generated by Django 4.0.1 on 2022-01-19 00:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_words_frequency_alter_game_id_alter_user_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4b38fd5a-1d49-4c6c-95af-efe91242bd9c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f486f395-4804-4fbd-818b-805de39d6ee7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
