# Generated by Django 4.0.1 on 2022-01-19 00:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0006_rename_words_word_alter_game_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bd04ecf5-28d9-419c-9bc7-ee8364258c10'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('26d5398a-4173-443e-b1e6-63c730f4b20d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
